//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Quan_Ly_Sinh_Vien.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBuoiDiemDanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBuoiDiemDanh()
        {
            this.tblDiemDanhs = new HashSet<tblDiemDanh>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MaLHP { get; set; }
        public Nullable<System.DateTime> NgayDD { get; set; }
        public Nullable<System.DateTime> HanDD { get; set; }
    
        public virtual tblLopHocPhan tblLopHocPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiemDanh> tblDiemDanhs { get; set; }
    }
}
