//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Quan_Ly_Sinh_Vien.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tblBaiTap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBaiTap()
        {
            this.tblNopBaiTaps = new HashSet<tblNopBaiTap>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MaLHP { get; set; }
        public string TenBT { get; set; }
        public string DeBai { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<System.DateTime> HanNop { get; set; }
        public Nullable<double> TyLe { get; set; }
        public HttpPostedFileBase File { get; set; }

        public virtual tblLopHocPhan tblLopHocPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNopBaiTap> tblNopBaiTaps { get; set; }
    }
}
