//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Quan_Ly_Sinh_Vien.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFriend
    {
        public long NguoiGui { get; set; }
        public long NguoiNhan { get; set; }
        public Nullable<long> LastMsg { get; set; }
        public Nullable<System.DateTime> Update_At { get; set; }
    
        public virtual tblTinNhan tblTinNhan { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
