//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Quan_Ly_Sinh_Vien.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLopHocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLopHocPhan()
        {
            this.tblBaiTaps = new HashSet<tblBaiTap>();
            this.tblBuoiDiemDanhs = new HashSet<tblBuoiDiemDanh>();
            this.tblDiems = new HashSet<tblDiem>();
            this.tblNhomChats = new HashSet<tblNhomChat>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MaHP { get; set; }
        public Nullable<int> MaNganh { get; set; }
        public string TenLHP { get; set; }
        public Nullable<long> MaGV { get; set; }
        public Nullable<System.DateTime> TGBatDau { get; set; }
        public Nullable<System.DateTime> TGKetThuc { get; set; }
        public string NamHoc { get; set; }
        public Nullable<int> HocKy { get; set; }
        public Nullable<double> TyLeDiemDD { get; set; }
        public Nullable<double> TyLeDiemBT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBaiTap> tblBaiTaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBuoiDiemDanh> tblBuoiDiemDanhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiem> tblDiems { get; set; }
        public virtual tblHocPhan tblHocPhan { get; set; }
        public virtual tblNganhHoc tblNganhHoc { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhomChat> tblNhomChats { get; set; }
    }
}
