//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Quan_Ly_Sinh_Vien.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tblNhomChat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhomChat()
        {
            this.tblChiTietNhomChats = new HashSet<tblChiTietNhomChat>();
            this.tblTinNhans = new HashSet<tblTinNhan>();
        }
    
        public long Id { get; set; }
        public string TenNhom { get; set; }
        public string Avatar { get; set; }
        public Nullable<System.DateTime> Create_At { get; set; }
        public Nullable<long> LastMsg { get; set; }
        public Nullable<System.DateTime> Update_At { get; set; }
        public Nullable<int> MaLHP { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietNhomChat> tblChiTietNhomChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTinNhan> tblTinNhans { get; set; }
        public virtual tblTinNhan tblTinNhan { get; set; }
        public virtual tblLopHocPhan tblLopHocPhan { get; set; }
    }
}
