//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Quan_Ly_Sinh_Vien.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblChiTietNhomChats = new HashSet<tblChiTietNhomChat>();
            this.tblDiems = new HashSet<tblDiem>();
            this.tblDiemDanhs = new HashSet<tblDiemDanh>();
            this.tblLopHocPhans = new HashSet<tblLopHocPhan>();
            this.tblNopBaiTaps = new HashSet<tblNopBaiTap>();
            this.tblTinNhans = new HashSet<tblTinNhan>();
            this.tblTinNhans1 = new HashSet<tblTinNhan>();
            this.tblFriends = new HashSet<tblFriend>();
            this.tblFriends1 = new HashSet<tblFriend>();
        }
    
        public long Id { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string MaSV { get; set; }
        public Nullable<int> MaLop { get; set; }
        public Nullable<int> MaNganh { get; set; }
        public string TrinhDo { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string CCCD { get; set; }
        public string SDT { get; set; }
        public string MatKhau { get; set; }
        public string GhiChu { get; set; }
        public string Anh { get; set; }
        public bool TrangThai { get; set; }
        public string Quyen { get; set; }
        public string ConnectionId { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietNhomChat> tblChiTietNhomChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiem> tblDiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiemDanh> tblDiemDanhs { get; set; }
        public virtual tblLop tblLop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLopHocPhan> tblLopHocPhans { get; set; }
        public virtual tblNganhHoc tblNganhHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNopBaiTap> tblNopBaiTaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTinNhan> tblTinNhans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTinNhan> tblTinNhans1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFriend> tblFriends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFriend> tblFriends1 { get; set; }
    }
}
